# ---------------------------
# SPLEEF MINI-GAME PLUGIN
# CONFIGURATION FILE
# Version 1.5.3
# ---------------------------
# specify language to use
language: "EN"
run_selftest_message: "YES"
# ---------------------------------
# Enforce Player alway goto server lobby
# Default is OFF 
# spawn on map savespawn location
# ---------------------------------
enable_spaw_lobby: "NO"
# ---------------------------
# added in jan.31.2015
# prevent regular player destroy arena blocks other than snow blocks
disable_Spleef_world_blockBreak: true
disable_Spleef_world_blockPlace: true
# ---------------------------------
server_lobby_world: "world"
server_lobby_x: "489"
server_lobby_y: "5"
server_lobby_z: "388"
# ---------------------------------
# EnableGame Self-Reset 
# set to YES to turn-on
# otherwise set to NO for manual
# ---------------------------------
enable_self_reset: "YES"
# ---------------------------------
# Game Reset Time out in Seconds
# ---------------------------------
reset_timeout: "120"
# ---------------------------------
# Reset Option: FLOOR OR FULL
# ---------------------------------
reset_option: "FLOOR"
# ---------------------------------
spleef_home_world: "world"
spleef_home_x: "502"
spleef_home_y: "4"
spleef_home_z: "412"
#----------------------------------
# Spleef Arena Location
#---------------------------------- 
spleef_arena_name: "Spleef Self-Generate Arena"
spleef_arena_size: "16"
spleef_arena_x: "535"
spleef_arena_y: "4"
spleef_arena_z: "409"
#------------------------------------
# Arena Player Entrace When on Join
#------------------------------------
spleef_arena_entrance_x: "542"
spleef_arena_entrance_y: "22"
spleef_arena_entrance_z: "430"
#
# Game Join Buttton Location
#---------------------------
spleef_join_button_1_x: "522"
spleef_join_button_1_y: "5"
spleef_join_button_1_z: "418"
#---------------------------
# Game Start Buttton Location
#---------------------------
spleef_start_button_1_x: "537"
spleef_start_button_1_y: "22"
spleef_start_button_1_z: "408"
# -------------------------------
# SPLEEF STATIC ACTION SIGNS
# -------------------------------
# STATIC SIGN GOTO LOBBY LOCATION
# -------------------------------
spleef_sign_lobby_x: "487"
spleef_sign_lobby_y: "5"
spleef_sign_lobby_z: "387"
# ------------------------------
# STATIC SIGN GOTO HOME LOCATION
# ------------------------------
spleef_sign_home_x: "487"
spleef_sign_home_y: "5"
spleef_sign_home_z: "388"
# ------------------------------
# STATIC SIGN JOIN ARENA
# ------------------------------
spleef_sign_join_x: "496"
spleef_sign_join_y: "5"
spleef_sign_join_z: "412"
# ------------------------------
# STATIC SIGN START GAME
# ------------------------------
spleef_sign_start_x: "487"
spleef_sign_start_y: "5"
spleef_sign_start_z: "386"
# ------------------------------
# STATIC SIGN VIEW STATS
# ------------------------------
spleef_sign_stats_x: "496"
spleef_sign_stats_y: "5"
spleef_sign_stats_z: "411"
# ------------------------------